require: rubocop

AllCops:
  Exclude:
    - 'bin/*'
    - 'config.ru'
    - 'config/spring.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/LineLength:
  Max: 99
  Exclude:
    - 'Gemfile'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'spec/**/**/**/*'
    - '**/**/config/environments/*'
    - '**/**/config/initializers/*'
    - '**/**/spec/**/**/**/*'
   
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/**/**/*'
    - '**/**/spec/**/**/**/*'

Rails/Output:
  Exclude:
    - 'db/*.rb'

Rails/FilePath:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'spec/rails_helper.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/migrate/*.rb'

Style/NegatedIf:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false