---
http_interactions:
- request:
    method: post
    uri: https://demo.vcp.vet/cwa/api/contractApplication
    body:
      encoding: UTF-8
      string: ''
    headers:
      Authorization:
      - Bearer eyJhbGciOiJIUzI1NiJ9.eyJwcmluY2lwYWwiOiJINHNJQUFBQUFBQUFBSlZTVDJzVFFSejliVXhwb1JCYlFjVkRCYkhlWkFOVmFFc3VqY3Vxa2UwbTVJK0hDb2JKN25TZGRuWm1uSmxOazR2a3BJY2VLbXBCOEN2MG02Z0hQNERvd1d2UFhwM1pcL3Rub3BUaW41YzJiOTk3djlcL2JvR0dhVWhIdUpSSVFxVjlBc0ljeFZRaEtXS0J4bGt1aXhteWtzWTZ4enhxT2MyRE1JbkJ5bkJFNEFKUkpydUJMc29DR3FVc1NTYW5Pd2d5TmRHMGxZNFRJNVZkeVdLTVY3WE82NjU5b1JsXC9ndmcwTGEyU2pCN0JZc29pamlHZE1oWlwvNUlFSW5qTFZnb3NJQkh1eGE2R3BrYnpEUkJWRTFUWnpGREE0cmpBT1pScGw5dzQwcXcwbkQ1Skd5bUNhMTJzSzRGTUNlUVVpYmRQNU4wdEkxdTcyMU1aaVo0Q2ErZ1BCS09PV1ozZHl6VnRUcXV4eWsxVXhQTzFIS1BwVHdtMjhTYUdcLzNKMHJ0dkI1OG12UktBMmNuZGk5OFUrSTBITVBuOFwvUGZOZk5GT3BPSGFWUFNDVmhzSmsyYXhVTzVLYkoyXC9mMnk5UHp4KzgreVNjYmFNaFwvXC9meDNMOWRITmpqNmNDU2FUNVZFZEdkcTlzdmt0R2ZPTmk4Yk1XeHZaZllockg1K0tOVk5CQzFneGJscHllYlZ2RFhMc1orUDE2cTZFc1ZORndLd2MyXC9iYjN1QjUyK3gyXC9cL2JUaCtYMnZHWFo2bTYxdW94bmFaNVVoRVVpUXRkVzE5ZFg3NnlzbVpDWGZrUzNYRGJpcGR2XC9YMnk4SHQzOFl5eWN3TTBRMHc2YWloWUlVWnVrQXk5ZEhoMHZ6SDM3dTV3UG5LZHRmclwvOEJaMXc1WUVBREFBQT0iLCJzdWIiOiJ2aXBhcGk4Nzg5NzQ5MiIsImV4cCI6MTU3MTk0NzMyNCwiaWF0IjoxNTcxOTQzNzI0LCJyb2xlcyI6WyJST0xFX0FQSSIsIlJPTEVfTUVSQ0hBTlRfU0VSVklDRV9DT05TVU1QVElPTiJdfQ.jvyU8TrPF8mcbxrJO9e1-oL4z_uGoCGrfuh7uKX1yeI
      User-Agent:
      - Faraday v0.15.4
      Content-Length:
      - '0'
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Server:
      - Apache-Coyote/1.1
      Www-Authenticate:
      - Bearer error="invalid_token"
      Content-Length:
      - '0'
      Date:
      - Mon, 28 Oct 2019 18:24:33 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Mon, 28 Oct 2019 18:24:33 GMT
recorded_with: VCR 3.0.3
