version: 2
workflows:
  version: 2
  application:
    jobs:
      - build
      - code_lint:
          requires:
            - build
      - code_security_scan:
          requires:
            - build
      # - dependency_security_scan:
      #     requires:
      #       - build
      - test-main-app:
          requires:
            - build
      - test-wellness-component:
          requires:
            - build

dockers:
  # https://circleci.com/docs/2.0/circleci-images/
  - &ruby_docker
    image: circleci/ruby:2.6.4
    environment:
      RAILS_ENV: test
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
  - &redis_docker
    image: circleci/redis

setup_steps:
  - &attach
    attach_workspace:
      at: /home/circleci
  - &ensure_bundler_version
    run:
      name: Upgrade Bundler
      command: |
        gem update --system
        gem --version
        gem uninstall bundler
        gem install bundler
        bundler --version
      working_directory: ~/

jobs:
  build:
    docker:
      - *ruby_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-v1-{{ checksum "Gemfile.lock" }}
            - bundle-v1
      - *ensure_bundler_version
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  code_lint:
    docker:
      - *ruby_docker
    steps:
      - *attach
      - *ensure_bundler_version
      - run:
          name: Rubocop
          command: bundle exec rubocop --list-target-files

  code_security_scan:
    docker:
      - *ruby_docker
    steps:
      - *attach
      - run:
          name: Brakeman
          command: sh .circleci/exec_brakeman.sh --exit-on-warn -w3
      - store_artifacts:
          path: tmp/brakeman.html

  dependency_security_scan:
    docker:
      - *ruby_docker
    steps:
      - *attach
      - run:
          name: Bundle-Audit
          command: sh .circleci/exec_bundle_audit.sh

  test-main-app:
    docker:
      - *ruby_docker
      - *redis_docker
    steps:
      - *attach
      - *ensure_bundler_version
      - run:
          name: Rspec
          command: bundle exec rspec spec -f d

  test-wellness-component:
    working_directory: ~/project/components/wellness
    docker:
      - *ruby_docker
      - *redis_docker
    steps:
      - *attach
      - *ensure_bundler_version
      - run:
          name: Where
          command: pwd
      - run:
          name: Bundle component
          command: bundle install
      - run:
          name: Rspec
          command: bundle exec rspec spec -f d
