default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_gateway_development

test:
  <<: *default
  database: api_gateway_test

staging:
  url: <%= ENV["DATABASE_URL"] %>

production:
  url: <%= ENV["DATABASE_URL"] %>
