---
http_interactions:
- request:
    method: get
    uri: https://demo.vcp.vet/cwa/api/contractApplication/1000008890
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer eyJhbGciOiJIUzI1NiJ9.eyJwcmluY2lwYWwiOiJINHNJQUFBQUFBQUFBSlZTVDJzVFFSejliVXhwb1JCYlFjVkRCYkhlWkFOVmFFc3VqY3Vxa2UwbTVJK0hDb2JKN25TZGRuWm1uSmxOazR2a3BJY2VLbXBCOEN2MG02Z0hQNERvd1d2UFhwM1pcL3Rub3BUaW41YzJiOTk3djlcL2JvR0dhVWhIdUpSSVFxVjlBc0ljeFZRaEtXS0J4bGt1aXhteWtzWTZ4enhxT2MyRE1JbkJ5bkJFNEFKUkpydUJMc29DR3FVc1NTYW5Pd2d5TmRHMGxZNFRJNVZkeVdLTVY3WE82NjU5b1JsXC9ndmcwTGEyU2pCN0JZc29pamlHZE1oWlwvNUlFSW5qTFZnb3NJQkh1eGE2R3BrYnpEUkJWRTFUWnpGREE0cmpBT1pScGw5dzQwcXcwbkQ1Skd5bUNhMTJzSzRGTUNlUVVpYmRQNU4wdEkxdTcyMU1aaVo0Q2ErZ1BCS09PV1ozZHl6VnRUcXV4eWsxVXhQTzFIS1BwVHdtMjhTYUdcLzNKMHJ0dkI1OG12UktBMmNuZGk5OFUrSTBITVBuOFwvUGZOZk5GT3BPSGFWUFNDVmhzSmsyYXhVTzVLYkoyXC9mMnk5UHp4KzgreVNjYmFNaFwvXC9meDNMOWRITmpqNmNDU2FUNVZFZEdkcTlzdmt0R2ZPTmk4Yk1XeHZaZllockg1K0tOVk5CQzFneGJscHllYlZ2RFhMc1orUDE2cTZFc1ZORndLd2MyXC9iYjN1QjUyK3gyXC9cL2JUaCtYMnZHWFo2bTYxdW94bmFaNVVoRVVpUXRkVzE5ZFg3NnlzbVpDWGZrUzNYRGJpcGR2XC9YMnk4SHQzOFl5eWN3TTBRMHc2YWloWUlVWnVrQXk5ZEhoMHZ6SDM3dTV3UG5LZHRmclwvOEJaMXc1WUVBREFBQT0iLCJzdWIiOiJ2aXBhcGk4Nzg5NzQ5MiIsImV4cCI6MTU3MjA1NDUzOSwiaWF0IjoxNTcyMDUwOTM5LCJyb2xlcyI6WyJST0xFX0FQSSIsIlJPTEVfTUVSQ0hBTlRfU0VSVklDRV9DT05TVU1QVElPTiJdfQ.CnA_dWHb6WNGpb5i-5jPGM-lWO4Px2fk_rJ0uVGfvN4
      User-Agent:
      - Faraday v0.15.4
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Apache-Coyote/1.1
      Set-Cookie:
      - JSESSIONID=054831C54CD628F076FDF18E5D68F843; Path=/cwa/; Secure; HttpOnly
      - cwa.cssName.null=loginmain.390; Expires=Thu, 13-Nov-2087 04:03:07 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Transfer-Encoding:
      - chunked
      Date:
      - Sat, 26 Oct 2019 00:48:59 GMT
    body:
      encoding: UTF-8
      string: '{"id":1000008890,"plan":{"id":5428459,"shortDescription":"Adult Dog
        Wellness Plan"},"primaryCareProfessional":{"id":5428395,"firstName":"Sam","middleName":"XXX","lastName":"Jones"},"initiatedByProfessional":{"id":5428394,"firstName":"Jane","middleName":null,"lastName":"Smith"},"accountNbrForDisplay":"8265","address1":"25
        Grove Place","address2":null,"ageGroupId":null,"bankAccountHolderType":"P","bankAccountType":"C","bankRoutingNbr":"122000496","chargeCreditCheckFeeToConsumer":false,"chargePaymentFeeToConsumer":false,"checkNbr":"123","city":"Irvine","contractDocCreated":false,"contractType":3,"country":"USA","createdByExternalUserCd":null,"creditCheckFeeAmt":10,"dateCreated":"2019-02-01T21:58:48Z","downPaymentAmount":25.00,"email":"Samuel.Hall@ExtendCredit.com","expirationMonth":null,"expirationYear":null,"externalClientCd":"1000","externalLocationCd":null,"externalMemberCd":"1002","externalPaymentProfileId":"100655799","externalPlanCd":null,"firstBillingDate":"2019-02-01T00:00:00Z","firstName":"Samuel","gatewayVaultId":null,"gender":null,"initialPaymentOption":2,"initiatedByProfessionalCd":null,"initiatedByProfessionalId":5428394,"institutionName":"UNION
        BANK","lastName":"Hall","lastUpdated":"2019-02-01T21:58:58Z","location":{"id":5426720,"accountCd":"010265","address1":"250
        Commerce","address2":"Suite 200 XXX","city":"Irvine","country":"USA","externalLocationCd":"010265","name":"SampleLocation","postalCode":"92602","resellerCustomerId":1995,"state":"CA"},"locationId":5426720,"memberAge":"1","memberName":"Rocky","middleInitial":null,"optionalPlanServices":[{"class":"com.bwse.model.api.ContractApplicationService","id":5429566,"companyCd":"264","contractApplication":{"class":"com.bwse.model.api.ContractApplication","id":1000008890},"datasetId":"264","dateCreated":"2019-02-01T21:58:48Z","discountPrice":null,"discountPriceTaxAmt":null,"lastUpdated":"2019-02-01T21:58:48Z","planService":{"class":"com.bwse.model.api.PlanService","id":5428888},"planYear":1,"retailPrice":null,"retailPriceTaxAmt":null,"selected":true,"serviceQty":null,"serviceType":null}],"payMethod":"ACH","payOption":"ACH","paymentAddress1":null,"paymentAddress2":null,"paymentAmount":19.53,"paymentCity":null,"paymentCountry":"USA","paymentName":"Samuel
        Hall","paymentPostalCode":null,"paymentServiceFeeAmt":3,"paymentState":null,"paymentTermCycle":"M","paymentTermDuration":12,"paymentaddressSameAsAccount":true,"phone1":"9494814601","phone1Type":"H","phone2":"9494814602","phone2Type":"W","planAmount":234.40,"planId":5428459,"portalUsername":"Samuel.Hall@ExtendCredit.com","postalCode":"92612","primaryCareProfessionalCd":null,"primaryCareProfessionalId":5428395,"salutation":"Mr.","securityCode":null,"sendNotifications":true,"setupFeeAmt":10,"speciesId":1,"state":"CA","status":"5","totalCostAmount":259.40,"userId":5426453}'
    http_version: 
  recorded_at: Sat, 26 Oct 2019 00:49:00 GMT
recorded_with: VCR 3.0.3
