---
http_interactions:
- request:
    method: get
    uri: https://demo.vcp.vet/cwa/api/contractApplication
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.15.4
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Server:
      - Apache-Coyote/1.1
      Www-Authenticate:
      - Bearer
      Content-Length:
      - '0'
      Date:
      - Mon, 28 Oct 2019 19:49:44 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Mon, 28 Oct 2019 19:49:45 GMT
recorded_with: VCR 3.0.3
