agreements:
  show:
    method: get
    resource: contractApplicationAgreement

  update:
    method: put
    resource: contractApplicationAgreement

contract_applications:
  index:
    method: get
    resource: contractApplication

  show:
    method: get
    resource: contractApplication

plans:
  index:
    method: get
    resource: plans